### ISSUE TITLE
Does pairing a device to the Schellenberg stick ADD or REPLACE the pairing?

### ISSUE THREAD

**Issue by mh166** [Hypfer/schellenberg-qivicon-usb#7]
I just found your docs. Very well done, thank you so much!

I'm curious: when pairing a device to the stick, will this _add_ another pairing - i.e., leaving the ability to control the shades with the hardware remote intact? Or does it _replace_ the binding, leaving the remote not useable anymore?

And if the latter is the case: how could I re-pair it to the remote, after tinkering with the stick? Because I suppose, unless you maybe have an initial implementation of this protocol, it probably is a longer running project for me to get this to work. So I would want to be able to fall back to the hw remote in the meantime. :)

**Comment by Hypfer** [comment]
Honestly no idea how that works exactly but I can report that I'm able to control my blinds both with the stick and the previously connected remote.
There could be some limits regarding the maximum amount of devices though.
Maybe even type-based? Like one remote and one usb stick?

**Comment by mh166** [comment]
One stick, one remote is absolutely sufficent. Thanks for letting me know. 😊👍 

I just want to make sure that the WAF -the "wife acceptance factor"- doesn't drop while I tinker with this.  😉

**Comment by LoPablo** [comment]
If i remember correctly, i managed to kick out the original remote while researching the protocol, after paring like five or more times with different enumerators. But re pairing just kicks out the oldest paired device (also from my somewhat bad memory)
